site_name: Contributing To Open Source
site_url: https://github.com/HealthCatalystSLC/contributing-to-open-source
repo_url: https://github.com/HealthCatalystSLC/contributing-to-open-source

theme: readthedocs
docs_dir: docs

pages:
- Branch: index.md
- DataMart 1:
  - 'Table':
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
  - 'Table':
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
  - 'Table':
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
  - 'Table':
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
  - 'Table':
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
    - 'Entity1': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
  - 'Table': 'foo/foo.md'
- DataMart 2:
  - 'More Levels': 'foo/foo.md'
- Install Tools: first_steps_install_tools.md
- Terminology: terminology.md
- Workflow: workflow.md
- Helpful Hints: helpful_hints.md
- Nav:
    - 'Nav': 'index.md'
    - Nav:
        - 'Nav': 'index.md'
        - Nav:
            - 'Nav': 'index.md'
            - 'Nav': 'index.md'
            - Nav:
                - Nav: 'index.md'
                - Nav: 'index.md'
                - Nav:
                    - 'Nav': 'index.md'
                    - 'Nav': 'index.md'
                    - Nav:
                        - 'Nav': 'index.md'
                        - 'Nav': 'index.md'
