site_name: Contributing To Open Source
site_url: https://github.com/HealthCatalystSLC/contributing-to-open-source
repo_url: https://github.com/HealthCatalystSLC/contributing-to-open-source

theme: readthedocs
docs_dir: docs

pages:
    - Workshop 1: workshop1.md
    - Install Tools: first_steps_install_tools.md
    - Terminology: terminology.md
    - Workflow: workflow.md
    - Helpful Hints: helpful_hints.md